---
title: "Binge drinking"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(hrbrthemes)
theme_set(theme_ipsum_rc())

library(boot)
library(broom)

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 8,
                      fig.height = 5)
```

```{r}
sat_gpa = read_csv(here::here("data/sat-gpa.csv"), col_types = "iidd") %>%
  rename("Math" = math_SAT, "Verb" = verb_SAT, "Comp" = comp_GPA, "Geral" = univ_GPA)
                  

glimpse(sat_gpa)
```


```{r}
sat_gpa %>%
  pivot_longer(c(Math, Verb), values_to = "SAT") %>%
  ggplot(aes(x=SAT, y=Comp )) +
    geom_point(alpha=.5, size=2)+
    ylab("Computation GPA") +
    facet_wrap(~name) +
    geom_smooth(method = "lm", se = FALSE)+
    theme(plot.title=element_text(hjust=0.5), text=element_text(size=12))
ggsave("figure1.png", width = 8, height = 5, dpi=600)
```

```{r}

sat_gpa %>%
  pivot_longer(c(Math, Verb), values_to = "SAT") %>%
  ggplot(aes(x=SAT )) +
    geom_histogram(fill = "steelblue", binwidth = 20, color = "black", alpha = .5) + 
    ylab("Quantidade") +
    xlab("SAT") +
    facet_wrap(~name) +
    theme(plot.title=element_text(hjust=0.5), text=element_text(size=12))
ggsave("figure2.png", width = 8, height = 5, dpi=600)
```

```{r}

sat_gpa %>%
  pivot_longer(c(Comp, Geral), values_to = "GPA") %>%
  ggplot(aes(x=GPA )) +
    geom_histogram(fill = "steelblue", binwidth = .1, color = "black", alpha = .5) + 
    ylab("Quantidade") +
    xlab("GPA") +
    facet_wrap(~name) +
    theme(plot.title=element_text(hjust=0.5), text=element_text(size=12))
ggsave("figure3.png", width = 8, height = 5, dpi=600)
```

```{r}
theta_math <- function(d, i) {
    r = d %>% 
        slice(i) %>% 
        summarise(r = cor(Math, Comp, method = "pearson")) %>%
        pull(r)
    r
}
ci_math = boot(data = sat_gpa,
           statistic = theta_math,
           R = 2000) %>%
    tidy(conf.level = .95,
         conf.method = "bca",
         conf.int = TRUE)
ci_math
```
```{r}
theta_verb <- function(d, i) {
    r = d %>% 
        slice(i) %>% 
        summarise(r = cor(Verb, Comp, method = "pearson")) %>%
        pull(r)
    r
}
ci_verb = boot(data = sat_gpa,
           statistic = theta_verb,
           R = 2000) %>%
    tidy(conf.level = .95,
         conf.method = "bca",
         conf.int = TRUE)
ci_verb
```
```{r}
cis = bind_rows(.id='name', "Verb" = ci_verb, "Math" = ci_math)
cis
```
```{r}
cis %>%
    ggplot(aes(y=name, x=statistic, xmin=conf.low, xmax=conf.high)) +
    geom_linerange() +
    geom_point(size=3) +
    xlab("Coeficiente de Pearson (r)") + 
    ylab("SAT") +
    theme(plot.title=element_text(hjust=0.5), text=element_text(size=12))
    geom_point(size=3)
ggsave("figura.4.png", width=8, height = 5, dpi=600)
```

```{r}
cor.test(sat_gpa$Math, sat_gpa$Comp) %>%
  tidy()
```
```{r}
cor.test(sat_gpa$Verb, sat_gpa$Comp) %>%
  tidy()
```

